apiVersion: v1
kind: Pod
metadata:
  name: test-pod2
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["sleep", "infinity"]
    envFrom:
    - configMapRef:
        name: my-config
